### ISSUE TITLE
Functions registered with registerWalker do not work

### ISSUE THREAD

**Issue by nuintun** [shellscape/postcss-values-parser#52] opened 2018-03-17 00:26 UTC
* Node Version: 9.8.0
* NPM Version: 5.6.0
* postcss-values-parser Version: 1.4.0

This issue is regarding a problem with:
- [x] Standard CSS
- [ ] LESS
- [ ] SCSS
- [ ] SASS

See: #50 

```js
const source = '/*1*/ 5px /* 2 */';
const ast = new Parser(source).parse();

ast.first.walkComments(node => {
  console.log(node.value);
});
```

[RunKit Example](https://runkit.com/nuintun/5aa88196d8f9eb0012694398)

**Comment by shellscape** [comment] 2018-03-17 12:50
Duplicate of #50

**Closed by shellscape** 2018-03-17 12:50 UTC
Labels: duplicate

**Comment by nuintun** [comment] 2018-03-18 00:44
@shellscape  Does this bug don't want to fix it?
